services:
  - type: web
    name: cbr-prediction-api
    runtime: python
    rootDir: .
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
